-- ============================================
-- DUMMY TEACHERS DATA GENERATOR
-- Requires the 'teachers' table to be created first.
-- Note: 'id' must be a valid UUID from auth.users if you want them to login.
-- For simple database population without login, we generate random UUIDs.
-- ============================================

INSERT INTO teachers (id, teacher_id, name, email, department, password, courses_taught, years_taught, subjects_taught, is_homeroom_teacher, homeroom_course, homeroom_year) VALUES
(gen_random_uuid(), 'T001', 'Dr. Alan Turing', 'alan.turing@cs.edu', 'Computer Science', 'password123', '{BCA, BSc}', '{First Year, Third Year}', '{Algorithms, Artificial Intelligence}', true, 'BCA', 'Third Year'),
(gen_random_uuid(), 'T002', 'Prof. Ada Lovelace', 'ada.lovelace@cs.edu', 'Computer Science', 'password123', '{BCA, B.Tech}', '{Second Year}', '{Programming, C++}', false, NULL, NULL),
(gen_random_uuid(), 'T003', 'Dr. Grace Hopper', 'grace.hopper@cs.edu', 'Computer Science', 'password123', '{BCA}', '{First Year}', '{COBOL, Software Engineering}', true, 'BCA', 'First Year'),
(gen_random_uuid(), 'T004', 'Prof. John von Neumann', 'john.neumann@math.edu', 'Mathematics', 'password123', '{BSc, B.Tech}', '{First Year, Second Year}', '{Calculus, Discrete Math}', false, NULL, NULL),
(gen_random_uuid(), 'T005', 'Dr. Richard Feynman', 'richard.feynman@phy.edu', 'Physics', 'password123', '{BSc}', '{Third Year}', '{Quantum Mechanics, Thermodynamics}', true, 'BSc', 'Third Year'),
(gen_random_uuid(), 'T006', 'Prof. Marie Curie', 'marie.curie@chem.edu', 'Chemistry', 'password123', '{BSc}', '{First Year, Second Year}', '{Physical Chemistry, Radioactivity}', false, NULL, NULL),
(gen_random_uuid(), 'T007', 'Dr. Isaac Newton', 'isaac.newton@phy.edu', 'Physics', 'password123', '{BSc, B.Tech}', '{First Year}', '{Mechanics, Optics}', true, 'BSc', 'First Year'),
(gen_random_uuid(), 'T008', 'Prof. Charles Darwin', 'charles.darwin@bio.edu', 'Biology', 'password123', '{BSc}', '{Second Year}', '{Evolutionary Biology, Genetics}', false, NULL, NULL),
(gen_random_uuid(), 'T009', 'Dr. Sigmund Freud', 'sigmund.freud@psych.edu', 'Psychology', 'password123', '{BA, BSc}', '{Third Year}', '{Psychoanalysis, Human Behavior}', true, 'BA', 'Third Year'),
(gen_random_uuid(), 'T010', 'Prof. Adam Smith', 'adam.smith@econ.edu', 'Economics', 'password123', '{BCom, BBA}', '{First Year, Third Year}', '{Microeconomics, Wealth of Nations}', false, NULL, NULL),
(gen_random_uuid(), 'T011', 'Dr. Karl Marx', 'karl.marx@history.edu', 'History', 'password123', '{BA}', '{Second Year}', '{Political Economy, European History}', true, 'BA', 'Second Year'),
(gen_random_uuid(), 'T012', 'Prof. Albert Einstein', 'albert.einstein@phy.edu', 'Physics', 'password123', '{BSc, PhD}', '{Third Year}', '{Relativity, Cosmology}', false, NULL, NULL),
(gen_random_uuid(), 'T013', 'Dr. Rosalind Franklin', 'rosalind.franklin@bio.edu', 'Biology', 'password123', '{BSc}', '{Second Year}', '{DNA Structure, Molecular Biology}', true, 'BSc', 'Second Year'),
(gen_random_uuid(), 'T014', 'Prof. Stephen Hawking', 'stephen.hawking@phy.edu', 'Physics', 'password123', '{BSc}', '{Third Year}', '{Black Holes, General Relativity}', false, NULL, NULL),
(gen_random_uuid(), 'T015', 'Dr. Nikola Tesla', 'nikola.tesla@eng.edu', 'Engineering', 'password123', '{B.Tech}', '{Final Year}', '{Electrical Engineering, AC Systems}', true, 'B.Tech', 'Final Year'),
(gen_random_uuid(), 'T016', 'Prof. Thomas Edison', 'thomas.edison@eng.edu', 'Engineering', 'password123', '{B.Tech}', '{First Year}', '{Innovation, Circuit Design}', false, NULL, NULL),
(gen_random_uuid(), 'T017', 'Dr. Carl Sagan', 'carl.sagan@astro.edu', 'Astronomy', 'password123', '{BSc}', '{First Year, Third Year}', '{Cosmos, Planetary Science}', false, NULL, NULL),
(gen_random_uuid(), 'T018', 'Prof. Jane Goodall', 'jane.goodall@bio.edu', 'Zoology', 'password123', '{BSc}', '{Third Year}', '{Primatology, Conservation}', true, 'BSc', 'Third Year'),
(gen_random_uuid(), 'T019', 'Dr. Tim Berners-Lee', 'tim.berners@cs.edu', 'Computer Science', 'password123', '{BCA, B.Tech}', '{Third Year}', '{Web Technologies, Networking}', false, NULL, NULL),
(gen_random_uuid(), 'T020', 'Prof. Linus Torvalds', 'linus.torvalds@cs.edu', 'Computer Science', 'password123', '{BCA}', '{Second Year}', '{Operating Systems, Linux Kernel}', true, 'BCA', 'Second Year'),
(gen_random_uuid(), 'T021', 'Dr. James Gosling', 'james.gosling@cs.edu', 'Computer Science', 'password123', '{BCA}', '{First Year, Second Year}', '{Java Programming, OOP}', false, NULL, NULL),
(gen_random_uuid(), 'T022', 'Prof. Guido van Rossum', 'guido.rossum@cs.edu', 'Computer Science', 'password123', '{BCA, BSc}', '{Third Year}', '{Python, Scripting Languages}', false, NULL, NULL),
(gen_random_uuid(), 'T023', 'Dr. Bjarne Stroustrup', 'bjarne.stroustrup@cs.edu', 'Computer Science', 'password123', '{B.Tech}', '{First Year}', '{C++, System Programming}', false, NULL, NULL),
(gen_random_uuid(), 'T024', 'Prof. Dennis Ritchie', 'dennis.ritchie@cs.edu', 'Computer Science', 'password123', '{BCA}', '{First Year}', '{C Programming, Unix}', true, 'BCA', 'First Year'),
(gen_random_uuid(), 'T025', 'Dr. Ken Thompson', 'ken.thompson@cs.edu', 'Computer Science', 'password123', '{B.Tech}', '{Second Year}', '{Operating Systems, Go}', false, NULL, NULL),
(gen_random_uuid(), 'T026', 'Prof. Donald Knuth', 'donald.knuth@cs.edu', 'Computer Science', 'password123', '{BCA, PhD}', '{Third Year}', '{Algorithms, TeX}', false, NULL, NULL),
(gen_random_uuid(), 'T027', 'Dr. Barbara Liskov', 'barbara.liskov@cs.edu', 'Computer Science', 'password123', '{BCA}', '{Third Year}', '{Software Design, Liskov Principle}', false, NULL, NULL),
(gen_random_uuid(), 'T028', 'Prof. Margaret Hamilton', 'margaret.hamilton@cs.edu', 'Computer Science', 'password123', '{B.Tech}', '{Final Year}', '{Software Engineering, Apollo Guidance}', true, 'B.Tech', 'Final Year'),
(gen_random_uuid(), 'T029', 'Dr. Katherine Johnson', 'katherine.johnson@math.edu', 'Mathematics', 'password123', '{BSc}', '{Second Year}', '{Orbital Mechanics, Geometry}', false, NULL, NULL),
(gen_random_uuid(), 'T030', 'Prof. Dorothy Vaughan', 'dorothy.vaughan@cs.edu', 'Computer Science', 'password123', '{BCA}', '{First Year}', '{Fortran, Supercomputing}', false, NULL, NULL),
(gen_random_uuid(), 'T031', 'Dr. Mary Jackson', 'mary.jackson@eng.edu', 'Engineering', 'password123', '{B.Tech}', '{Third Year}', '{Aerospace Engineering, Fluid Dynamics}', false, NULL, NULL),
(gen_random_uuid(), 'T032', 'Prof. Plato', 'plato@phil.edu', 'Philosophy', 'password123', '{BA}', '{First Year}', '{Ethics, Metaphysics}', false, NULL, NULL),
(gen_random_uuid(), 'T033', 'Dr. Aristotle', 'aristotle@phil.edu', 'Philosophy', 'password123', '{BA}', '{Second Year}', '{Logic, Rhetoric}', true, 'BA', 'Second Year'),
(gen_random_uuid(), 'T034', 'Prof. Socrates', 'socrates@phil.edu', 'Philosophy', 'password123', '{BA}', '{Third Year}', '{Socratic Method, Epistemology}', false, NULL, NULL),
(gen_random_uuid(), 'T035', 'Dr. Confucius', 'confucius@phil.edu', 'Philosophy', 'password123', '{BA}', '{First Year}', '{Moral Philosophy, Governance}', false, NULL, NULL),
(gen_random_uuid(), 'T036', 'Prof. Sun Tzu', 'sun.tzu@history.edu', 'History', 'password123', '{BA}', '{Second Year}', '{Military Strategy, Conflict Resolution}', false, NULL, NULL),
(gen_random_uuid(), 'T037', 'Dr. William Shakespeare', 'william.shakespeare@lit.edu', 'Literature', 'password123', '{BA}', '{First Year, Second Year}', '{Drama, Poetry}', true, 'BA', 'First Year'),
(gen_random_uuid(), 'T038', 'Prof. Jane Austen', 'jane.austen@lit.edu', 'Literature', 'password123', '{BA}', '{Third Year}', '{Victorian Novels, Social Commentary}', false, NULL, NULL),
(gen_random_uuid(), 'T039', 'Dr. Charles Dickens', 'charles.dickens@lit.edu', 'Literature', 'password123', '{BA}', '{Second Year}', '{Realism, Victorian Era}', false, NULL, NULL),
(gen_random_uuid(), 'T040', 'Prof. Virginia Woolf', 'virginia.woolf@lit.edu', 'Literature', 'password123', '{BA}', '{Third Year}', '{Modernism, Feminism}', false, NULL, NULL),
(gen_random_uuid(), 'T041', 'Dr. Maya Angelou', 'maya.angelou@lit.edu', 'Literature', 'password123', '{BA}', '{First Year}', '{Autobiography, Civil Rights}', false, NULL, NULL),
(gen_random_uuid(), 'T042', 'Prof. Ernest Hemingway', 'ernest.hemingway@lit.edu', 'Literature', 'password123', '{BA}', '{Second Year}', '{Short Stories, Modern Literature}', false, NULL, NULL),
(gen_random_uuid(), 'T043', 'Dr. F. Scott Fitzgerald', 'scott.fitzgerald@lit.edu', 'Literature', 'password123', '{BA}', '{Third Year}', '{Jazz Age, American Dream}', false, NULL, NULL),
(gen_random_uuid(), 'T044', 'Prof. George Orwell', 'george.orwell@lit.edu', 'Literature', 'password123', '{BA}', '{Second Year}', '{Dystopian Fiction, Political Satire}', true, 'BA', 'Second Year'),
(gen_random_uuid(), 'T045', 'Dr. J.R.R. Tolkien', 'jrr.tolkien@lit.edu', 'Literature', 'password123', '{BA}', '{Third Year}', '{Fantasy, Philology}', false, NULL, NULL),
(gen_random_uuid(), 'T046', 'Prof. C.S. Lewis', 'cs.lewis@lit.edu', 'Literature', 'password123', '{BA}', '{First Year}', '{Medieval Literature, Christian Apologetics}', false, NULL, NULL),
(gen_random_uuid(), 'T047', 'Dr. Agatha Christie', 'agatha.christie@lit.edu', 'Literature', 'password123', '{BA}', '{Third Year}', '{Mystery, Detective Fiction}', false, NULL, NULL),
(gen_random_uuid(), 'T048', 'Prof. Leo Tolstoy', 'leo.tolstoy@lit.edu', 'Literature', 'password123', '{BA}', '{Second Year}', '{Russian Literature, Realism}', false, NULL, NULL),
(gen_random_uuid(), 'T049', 'Dr. Fyodor Dostoevsky', 'fyodor.dostoevsky@lit.edu', 'Literature', 'password123', '{BA}', '{Third Year}', '{Psychological Fiction, Existentialism}', true, 'BA', 'Third Year'),
(gen_random_uuid(), 'T050', 'Prof. Mark Twain', 'mark.twain@lit.edu', 'Literature', 'password123', '{BA}', '{First Year}', '{American Literature, Humor}', false, NULL, NULL);

